# Generated by Django 2.2.3 on 2019-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kickstarter_Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backers', models.IntegerField()),
                ('blurb', models.CharField(max_length=135)),
                ('converted', models.IntegerField()),
            ],
        ),
    ]
