# Generated by Django 2.2.3 on 2019-08-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasacomment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
