# Generated by Django 2.2.3 on 2019-08-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_remove_todolist_listuserid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together=set(),
        ),
    ]
