# Generated by Django 2.2.3 on 2019-08-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_auto_20190810_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='listuserid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
