# Generated by Django 2.2.3 on 2019-08-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0008_auto_20190810_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='listitems',
        ),
        migrations.CreateModel(
            name='ToDoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todotest', models.TextField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do.ToDoList')),
            ],
        ),
    ]
