# Generated by Django 2.2.3 on 2019-08-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0009_auto_20190810_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_task', models.TextField()),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='to_do.ToDoList')),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoItems',
        ),
    ]
